# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.
# You can safely delete this file if you don't need it.

service-cluster-ip-range = "10.32.0.0/24"
service-node-port-range = "30000-32767"
secure-port = "6443"
[external]
name = ""
ip = ""
